# 교수님이 제시한 count 의사코드

```python
H, W = image.shape[:2]
counted = np.zeros_like(image)
cnt = 0
for h in range(H):
    for w in range(W):
        pixel = image[h,w]
        if pixel is not background but object:
            if the pixel is alread counted (counted[h,w] > 0):
                continue
            else:
                Generate a stack and insert the pixel idx [h,w] into the stack
                while the stack is not empty:
                    Pop one pixel idx up from the stack
                    Count this pixel with cnt and update counted matrix
                    Generate the neighbor list with 8 surrounding pixels
                    for pixel in the neighbor list:
                            if pixel is out of bound:
                                continue
                            elif pixel is already counted:
                                continue
                            elif pixel is background
                                continue
                            else:
                                Insert this pixel to the stack for counting
                Increase cnt by 1
print(cnt)        
print(counted)
```

# 내가 작성한 코드

# 테스트 이미지 생성

In [20]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

test_img = np.zeros((5,5), dtype = np.uint8)
test_img[1:4,1]=255
test_img[2,4]=255
test_img

array([[  0,   0,   0,   0,   0],
       [  0, 255,   0,   0,   0],
       [  0, 255,   0,   0, 255],
       [  0, 255,   0,   0,   0],
       [  0,   0,   0,   0,   0]], dtype=uint8)

# initialization

In [21]:
H,W = test_img.shape[:2]
H,W
counted = np.zeros_like(test_img)
cnt = 0

# 함수 생성

In [30]:
def cnt_obj(image):
    H, W = image.shape[:2]
    counted = np.zeros_like(image)
    cnt = 0
    pixels_to_check = []

    for h in range(H):
        for w in range(W):
            pixel = image[h, w]
            if pixel == 255:  # 픽셀이 obj이면
                if counted[h, w] > 0:
                    continue
                else:
                    pixels_to_check.append([h, w])
                    while pixels_to_check:
                        obj_h, obj_w = pixels_to_check.pop(0)
                        
                        if counted[obj_h, obj_w] > 0:
                            continue
                        counted[obj_h, obj_w] = 1
                        for i in range(-1, 2):
                            for j in range(-1, 2):
                                try:
                                    neighbor_pixel = image[obj_h + i, obj_w + j]
                                except IndexError:
                                    continue
                                if counted[obj_h + i, obj_w + j] > 0:
                                    continue
                                if neighbor_pixel == 0:
                                    continue
                                pixels_to_check.append([obj_h + i, obj_w + j])
                    cnt += 1

    print("Number of objects:", cnt)
    print("Counted matrix:")
    print(counted)


# 함수로 만든 코드

In [28]:
import numpy as np

def count_objects(image, background_color):
    H, W = image.shape[:2]
    counted = np.zeros_like(image)
    cnt = 0
    stack = []

    def is_background(pixel):
        return pixel == background_color

    def is_out_of_bound(h, w):
        return h < 0 or h >= H or w < 0 or w >= W

    for h in range(H):
        for w in range(W):
            pixel = image[h, w]
            if is_background(pixel):
                continue
            if counted[h, w] > 0:
                continue
            
            stack.append((h, w))
            while stack:
                curr_h, curr_w = stack.pop()
                if counted[curr_h, curr_w] > 0:
                    continue
                counted[curr_h, curr_w] = 1
                neighbors = [(curr_h + dh, curr_w + dw) for dh in range(-1, 2) for dw in range(-1, 2)]
                for nh, nw in neighbors:
                    if is_out_of_bound(nh, nw):
                        continue
                    if counted[nh, nw] > 0:
                        continue
                    if is_background(image[nh, nw]):
                        continue
                    stack.append((nh, nw))
            cnt += 1
    
    print("Number of objects:", cnt)
    print("Counted matrix:")
    print(counted)

# 테스트 이미지 실행 결과

In [33]:
test_img = np.zeros((5, 5), dtype=np.uint8)
test_img[1:4, 1] = 255
test_img[3, 3] = 255
test_img[1, 4] = 255

background_color = 0  # 배경이 0일때 검정일때
count_objects(test_img, background_color)

Number of objects: 3
Counted matrix:
[[0 0 0 0 0]
 [0 1 0 0 1]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]]


In [34]:
import numpy as np
import matplotlib.pyplot as plt


image = np.zeros((5,5), dtype = 'uint8')

image[1,1:3] = 255
image[1, 4] = 255
image[3:5, 2:4] = 255


background_color = 0  # 배경이 0일때 검정일때
count_objects(image, background_color)

Number of objects: 3
Counted matrix:
[[0 0 0 0 0]
 [0 1 1 0 1]
 [0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 1 1 0]]


# 실제 이미지 실행 결과

In [32]:
import cv2 
import matplotlib.pyplot as plt
import numpy as np

src= cv2.imread("mosquito.png",0)
h,w = src.shape
T = 100
dst = np.where(src >= T, 0,255) # 임계값보다 큰 경우를 0으로 작은 경우를 255로

dst= dst.astype(np.uint8)
background_color = 0  # 배경이 0일때 검정일때
count_objects(dst, background_color)

Number of objects: 460
Counted matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# 내가 만든 함수 실행

In [31]:
import cv2 
import matplotlib.pyplot as plt
import numpy as np

src= cv2.imread("mosquito.png",0)
h,w = src.shape
T = 100
dst = np.where(src >= T, 0,255) # 임계값보다 큰 경우를 0으로 작은 경우를 255로

dst= dst.astype(np.uint8)
background_color = 0  # 배경이 0일때 검정일때
cnt_obj(dst)

Number of objects: 460
Counted matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
